### ISSUE TITLE
Global parameter: _fields=_embedded[wp:term][1][0].name

### ISSUE THREAD

**Issue by LukaszJaro** [WP-API/docs#72]
Docs don't show example of how to do this, I'm still trying to figure it out:

https://developer.wordpress.org/rest-api/using-the-rest-api/global-parameters/#_fields

I can't filter _embedded fields.

**Comment by TimothyBJacobs** [comment]
The fallback fields filtering happens before the embedding happens, so this doesn't currently work.

Limiting the list of embedded fields is not currently supported. We're looking to change that in: https://core.trac.wordpress.org/ticket/39696

Only embedding a specific item of a given relation, ie only showing the first term is not currently planned. It'd be great to add this as a use case to the trac ticket above for consideration.

I'm going to close this out since this isn't a docs issue.

**Comment by LukaszJaro** [comment]
@TimothyBJacobs, thank you for the closure was going in circles with this!
